<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class EthSyncing extends Schema\Object\Base # generated by ClientGenerator based on schema.json
{
	public $startingBlock;
	public $currentBlock;
	public $highestBlock;

	public function __construct(
		?Schema\Primitive\Quantity $startingBlock = null,
		?Schema\Primitive\Quantity $currentBlock = null,
		?Schema\Primitive\Quantity $highestBlock = null
	){
		$this->startingBlock = $startingBlock;
		$this->currentBlock = $currentBlock;
		$this->highestBlock = $highestBlock;
	}
}
