<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class FilterChange extends Schema\Object\Base # generated by ClientGenerator based on schema.json
{
	public $removed;
	public $logIndex;
	public $transactionIndex;
	public $transactionHash;
	public $blockHash;
	public $blockNumber;
	public $address;
	public $data;
	public $topics;

	public function __construct(
		?bool $removed = null,
		?Schema\Primitive\Quantity $logIndex = null,
		?Schema\Primitive\Quantity $transactionIndex = null,
		?Schema\Primitive\Bytes32 $transactionHash = null,
		?Schema\Primitive\Bytes32 $blockHash = null,
		?Schema\Primitive\Quantity $blockNumber = null,
		?Schema\Primitive\Bytes20 $address = null,
		?Schema\Primitive\ArrayOrData $data = null,
		?array $topics = null
	){
		$this->removed = $removed;
		$this->logIndex = $logIndex;
		$this->transactionIndex = $transactionIndex;
		$this->transactionHash = $transactionHash;
		$this->blockHash = $blockHash;
		$this->blockNumber = $blockNumber;
		$this->address = $address;
		$this->data = $data;
		$this->topics = $topics;
	}
}
