<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class Filter extends Schema\Object\Base # generated by ClientGenerator based on schema.json
{
	public $fromBlock;
	public $toBlock;
	public $address;
	public $topics;

	public function __construct(
		?Schema\Primitive\QuantityOrTag $fromBlock = null,
		?Schema\Primitive\QuantityOrTag $toBlock = null,
		?Schema\Primitive\Bytes20 $address = null,
		?array $topics = null
	){
		$this->fromBlock = $fromBlock;
		$this->toBlock = $toBlock;
		$this->address = $address;
		$this->topics = $topics;
	}
}
