<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class Receipt extends Schema\Object\Base # generated by ClientGenerator based on schema.json
{
	public $transactionHash;
	public $transactionIndex;
	public $blockHash;
	public $blockNumber;
	public $cumulativeGasUsed;
	public $gasUsed;
	public $contractAddress;
	public $logs;

	public function __construct(
		?Schema\Primitive\Bytes32 $transactionHash = null,
		?Schema\Primitive\Quantity $transactionIndex = null,
		?Schema\Primitive\Bytes32 $blockHash = null,
		?Schema\Primitive\Quantity $blockNumber = null,
		?Schema\Primitive\Quantity $cumulativeGasUsed = null,
		?Schema\Primitive\Quantity $gasUsed = null,
		?Schema\Primitive\Bytes20 $contractAddress = null,
		?array $logs = null
	){
		$this->transactionHash = $transactionHash;
		$this->transactionIndex = $transactionIndex;
		$this->blockHash = $blockHash;
		$this->blockNumber = $blockNumber;
		$this->cumulativeGasUsed = $cumulativeGasUsed;
		$this->gasUsed = $gasUsed;
		$this->contractAddress = $contractAddress;
		$this->logs = $logs;
	}
}
