<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class Receipt extends Schema\Object # generated by ClientGenerator based on schema.json
{
	public $transactionHash;
	public $transactionIndex;
	public $blockHash;
	public $blockNumber;
	public $cumulativeGasUsed;
	public $gasUsed;
	public $contractAddress;
	public $logs;

	public function __construct(
		?Schema\Primitive\Bytes32 $transactionHash,
		?int $transactionIndex,
		?Schema\Primitive\Bytes32 $blockHash,
		?int $blockNumber,
		?int $cumulativeGasUsed,
		?int $gasUsed,
		?Schema\Primitive\Bytes20 $contractAddress,
		?array $logs
	){
		$this->transactionHash = $transactionHash;
		$this->transactionIndex = $transactionIndex;
		$this->blockHash = $blockHash;
		$this->blockNumber = $blockNumber;
		$this->cumulativeGasUsed = $cumulativeGasUsed;
		$this->gasUsed = $gasUsed;
		$this->contractAddress = $contractAddress;
		$this->logs = $logs;
	}
}
