<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class SHHFilterChange extends Schema\Object\Base # generated by ClientGenerator based on schema.json
{
	public $hash;
	public $from;
	public $to;
	public $expiry;
	public $ttl;
	public $sent;
	public $topics;
	public $payload;
	public $workProved;

	public function __construct(
		?Schema\Primitive\Bytes $hash = null,
		?Schema\Primitive\Bytes $from = null,
		?Schema\Primitive\Bytes $to = null,
		?Schema\Primitive\Quantity $expiry = null,
		?Schema\Primitive\Quantity $ttl = null,
		?Schema\Primitive\Quantity $sent = null,
		?array $topics = null,
		?Schema\Primitive\Bytes $payload = null,
		?Schema\Primitive\Quantity $workProved = null
	){
		$this->hash = $hash;
		$this->from = $from;
		$this->to = $to;
		$this->expiry = $expiry;
		$this->ttl = $ttl;
		$this->sent = $sent;
		$this->topics = $topics;
		$this->payload = $payload;
		$this->workProved = $workProved;
	}
}
