<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class SHHFilterChange extends Schema\Object # generated by ClientGenerator based on schema.json
{
	public $hash;
	public $from;
	public $to;
	public $expiry;
	public $ttl;
	public $sent;
	public $topics;
	public $payload;
	public $workProved;

	public function __construct(
		?Schema\Primitive\Bytes $hash,
		?Schema\Primitive\Bytes $from,
		?Schema\Primitive\Bytes $to,
		?int $expiry,
		?int $ttl,
		?int $sent,
		?array $topics,
		?Schema\Primitive\Bytes $payload,
		?int $workProved
	){
		$this->hash = $hash;
		$this->from = $from;
		$this->to = $to;
		$this->expiry = $expiry;
		$this->ttl = $ttl;
		$this->sent = $sent;
		$this->topics = $topics;
		$this->payload = $payload;
		$this->workProved = $workProved;
	}
}
