<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class SHHPost extends Schema\Object # generated by ClientGenerator based on schema.json
{
	public $from;
	public $to;
	public $topics;
	public $payload;
	public $priority;
	public $ttl;

	public function __construct(
		?Schema\Primitive\Bytes $from,
		?Schema\Primitive\Bytes $to,
		array $topics,
		Schema\Primitive\Bytes $payload,
		Schema\Primitive\Quantity $priority,
		Schema\Primitive\Quantity $ttl
	){
		$this->from = $from;
		$this->to = $to;
		$this->topics = $topics;
		$this->payload = $payload;
		$this->priority = $priority;
		$this->ttl = $ttl;
	}
}
