<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class Transaction extends Schema\Object # generated by ClientGenerator based on schema.json
{
	public $hash;
	public $nonce;
	public $blockHash;
	public $blockNumber;
	public $transactionIndex;
	public $from;
	public $to;
	public $value;
	public $gasPrice;
	public $gas;
	public $input;

	public function __construct(
		?Schema\Primitive\Bytes32 $hash,
		?int $nonce,
		?Schema\Primitive\Bytes32 $blockHash,
		?int $blockNumber,
		?int $transactionIndex,
		?Schema\Primitive\Bytes20 $from,
		?Schema\Primitive\Bytes20 $to,
		?int $value,
		?int $gasPrice,
		?int $gas,
		?Schema\Primitive\Bytes $input
	){
		$this->hash = $hash;
		$this->nonce = $nonce;
		$this->blockHash = $blockHash;
		$this->blockNumber = $blockNumber;
		$this->transactionIndex = $transactionIndex;
		$this->from = $from;
		$this->to = $to;
		$this->value = $value;
		$this->gasPrice = $gasPrice;
		$this->gas = $gas;
		$this->input = $input;
	}
}
