<?php namespace TooBasic\Ethereum\Schema\Object;
use TooBasic\Ethereum\Schema;

class Transaction extends Schema\Object\Base # generated by ClientGenerator based on schema.json
{
	public $hash;
	public $nonce;
	public $blockHash;
	public $blockNumber;
	public $transactionIndex;
	public $from;
	public $to;
	public $value;
	public $gasPrice;
	public $gas;
	public $input;

	public function __construct(
		?Schema\Primitive\Bytes32 $hash = null,
		?Schema\Primitive\Quantity $nonce = null,
		?Schema\Primitive\Bytes32 $blockHash = null,
		?Schema\Primitive\Quantity $blockNumber = null,
		?Schema\Primitive\Quantity $transactionIndex = null,
		?Schema\Primitive\Bytes20 $from = null,
		?Schema\Primitive\Bytes20 $to = null,
		?Schema\Primitive\Quantity $value = null,
		?Schema\Primitive\Quantity $gasPrice = null,
		?Schema\Primitive\Quantity $gas = null,
		?Schema\Primitive\Bytes $input = null
	){
		$this->hash = $hash;
		$this->nonce = $nonce;
		$this->blockHash = $blockHash;
		$this->blockNumber = $blockNumber;
		$this->transactionIndex = $transactionIndex;
		$this->from = $from;
		$this->to = $to;
		$this->value = $value;
		$this->gasPrice = $gasPrice;
		$this->gas = $gas;
		$this->input = $input;
	}
}
